<?php
/**
 * Smarty plugin
 * @package Smarty
 * @subpackage plugins
 */


/**
 * Smarty {counter} function plugin
 *
 * Type:     function<br>
 * Name:     counter<br>
 * Purpose:  print out a counter value
 * @link http://smarty.php.net/manual/en/language.function.counter.php {counter}
 *       (Smarty online manual)
 * @param array parameters
 * @param Smarty
 * @return string|null
 */


function smarty_function_round_textfield($params, &$smarty)
{
	$htmlObject = createRoundTextField($params, $smarty);
	return $htmlObject["html"];
}

function createRoundTextField($params, &$smarty) {
	require_once $smarty->_get_plugin_filepath('shared','escape_special_chars');
	require_once $smarty->_get_plugin_filepath('shared','unique_id');
	    
    $id = null;
    $name = null;
    $class = 'roundTextfield';
    $field = null;
    $value = '';
    $extra = '';
    $style = '';
    $tfClass = '';
    
    foreach($params as $_key=>$_value) {
    	switch($_key) {
    		case 'id':
    		case 'name':
    		case 'field':
    		case 'value':
    			$$_key = $_value;
    			break;
    			
    		case 'width':
    			$style .= 'width: '.$_value.'px;';
    			break;
    			
    		case 'class':
    			$class .= ' '.$_value;
    			break;
    			
    		case 'tfClass':
    			$tfClass .= ' '.$_value;
    			break; 
    		
    		default:
    			$extra .= ' '.$_key.'="'.smarty_function_escape_special_chars($_value).'"';
    			break;
    	}
    }
    
    $extra .= ' '.$tfClass;
    
	if ($name == null) {
    	throw new Exception("Specify name for autogenerated field with id '$name'");
    }
    
    if ($id == null) {
    	$id = uniqueId();
    }
    
    if($field){
		$name = $field;
		$value = $smarty->get_template_vars($name);
	}
    
	$html = '<div class="'.$class.'"><div class="tfStart">
				<input type="text" ' .
					'name="'.smarty_function_escape_special_chars($name).'" ' .
					'value="'.smarty_function_escape_special_chars($value).'" ' .
					'id="'.$id.'" ' .
					'style="'.$style.'"' .
					$extra .
				'/>
		</div>
		<div class="tfEnd"></div></div>';
	
	
	$result = array();
	$result["html"] = $html;
	$result["id"]	= $id;
	$result["name"]	= $name;
	$result["value"]	= $value;
	
	return $result;
					
}
/* vim: set expandtab: */

?>